<a href="https://colab.research.google.com/github/elfozge/data_science_bootcamp/blob/main/IndexingAndSlicingOfNumPyArrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

For the assignment, you are going to use [Earthquakes](https://bootrain-lms-assets.s3.eu-central-1.amazonaws.com/bootrain-lms-static/datasets/Earthquakes.csv) dataset.

**(1)** Load the Earthquakes dataset. Export the dataset to an array as you covered in the previous lesson.

In [ ]:
import pandas as pd
import numpy as np
deprem = np.loadtxt('Earthquakes.csv', delimiter=',')
print(deprem)

[[0.000e+00 0.000e+00 0.000e+00 ... 4.000e+00 7.000e+00 0.000e+00]
 [1.000e+00 0.000e+00 0.000e+00 ... 4.100e+00 7.000e+00 0.000e+00]
 [2.000e+00 0.000e+00 0.000e+00 ... 4.400e+00 7.000e+00 0.000e+00]
 ...
 [6.571e+03 4.000e+00 0.000e+00 ... 4.800e+00 2.000e+00 0.000e+00]
 [6.572e+03 3.000e+00 0.000e+00 ... 5.200e+00 2.000e+00 0.000e+00]
 [6.573e+03 2.000e+00 0.000e+00 ... 4.400e+00 2.000e+00 0.000e+00]]


**(2)** Slice first 20 rows and column numbers 3, 5, 6, 7, 12. Then, assign the array you sliced to a variable.

In [ ]:
data = deprem[:20, [3, 5, 6, 7, 12]]
print(data)

[[ 0.     36.8578 44.4161 16.97    4.    ]
 [ 0.     37.4341 35.852   7.02    4.1   ]
 [ 0.     37.6878 37.4016 10.27    4.4   ]
 [ 0.     37.2003 30.4376 78.07    4.    ]
 [ 0.     35.6846 26.7266 42.77    4.5   ]
 [ 0.     36.4171 28.6991 14.86    4.1   ]
 [ 0.     36.0535 31.2135 36.68    5.2   ]
 [ 0.     37.1958 30.6241 50.33    4.8   ]
 [ 0.     36.9653 27.7633  6.93    4.3   ]
 [ 0.     38.893  26.4483 11.62    4.2   ]
 [ 0.     37.3773 36.3855 10.53    4.8   ]
 [ 0.     35.8861 26.0695 28.49    4.9   ]
 [ 0.     37.4635 36.3113 15.29    4.3   ]
 [ 0.     37.0201 36.0845 10.      4.1   ]
 [ 0.     37.6546 26.6698  4.5     4.5   ]
 [ 0.     37.5318 29.848  17.58    4.6   ]
 [ 0.     39.0388 44.1533  7.52    4.5   ]
 [ 0.     38.357  44.8686 10.05    4.1   ]
 [ 0.     35.7018 28.1495  6.25    4.1   ]
 [ 0.     37.6883 37.3968 10.63    4.1   ]]


**(3)** Display the row numbers where last values are equal to 4.5 or higher.

In [ ]:
b = data[np.where(data[:,-1]>=4.5)]
print(b)

[[ 0.     35.6846 26.7266 42.77    4.5   ]
 [ 0.     36.0535 31.2135 36.68    5.2   ]
 [ 0.     37.1958 30.6241 50.33    4.8   ]
 [ 0.     37.3773 36.3855 10.53    4.8   ]
 [ 0.     35.8861 26.0695 28.49    4.9   ]
 [ 0.     37.6546 26.6698  4.5     4.5   ]
 [ 0.     37.5318 29.848  17.58    4.6   ]
 [ 0.     39.0388 44.1533  7.52    4.5   ]]


**(4)** Assign 1 to first row.

In [ ]:
b[0:1,:] = 1
print(b)

[[ 1.      1.      1.      1.      1.    ]
 [ 0.     36.0535 31.2135 36.68    5.2   ]
 [ 0.     37.1958 30.6241 50.33    4.8   ]
 [ 0.     37.3773 36.3855 10.53    4.8   ]
 [ 0.     35.8861 26.0695 28.49    4.9   ]
 [ 0.     37.6546 26.6698  4.5     4.5   ]
 [ 0.     37.5318 29.848  17.58    4.6   ]
 [ 0.     39.0388 44.1533  7.52    4.5   ]]


**(5)** Save the final state of the array to disk. You are going to use this in the next assignment.

In [ ]:
np.save("array_b.npy", b)

In [ ]:
# save işlemini kontrol edersek son haldeki array'e ulaştık
array = np.load("array_b.npy")
print(array)

[[ 1.      1.      1.      1.      1.    ]
 [ 0.     36.0535 31.2135 36.68    5.2   ]
 [ 0.     37.1958 30.6241 50.33    4.8   ]
 [ 0.     37.3773 36.3855 10.53    4.8   ]
 [ 0.     35.8861 26.0695 28.49    4.9   ]
 [ 0.     37.6546 26.6698  4.5     4.5   ]
 [ 0.     37.5318 29.848  17.58    4.6   ]
 [ 0.     39.0388 44.1533  7.52    4.5   ]]
