<a href="https://colab.research.google.com/github/elfozge/data_science_bootcamp/blob/main/BasicsOfNumPyArray.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**(1)** Create 3 lists representing house features, each list containing 10 values. First one for squaremeter of house, second one for rooms and last one for price. Then, create an array combining these lists.

In [ ]:
import numpy as np
squares_house = np.array([125, 90, 150, 100, 115, 80, 120, 150, 50, 100])
rooms_house = np.array ([3, 2, 4, 3, 3, 1, 2, 3, 1, 3])
price_house = np.array([4500, 1250, 5000, 2750, 3000, 1000, 2500, 2750, 800, 3000])

house = np.array([squares_house, rooms_house, price_house])
print(house)

[[ 125   90  150  100  115   80  120  150   50  100]
 [   3    2    4    3    3    1    2    3    1    3]
 [4500 1250 5000 2750 3000 1000 2500 2750  800 3000]]


**(2)** Transpose the array you have created, so that every line can represent features of one house.

In [ ]:
house_new = house.transpose()
print(house_new)

[[ 125    3 4500]
 [  90    2 1250]
 [ 150    4 5000]
 [ 100    3 2750]
 [ 115    3 3000]
 [  80    1 1000]
 [ 120    2 2500]
 [ 150    3 2750]
 [  50    1  800]
 [ 100    3 3000]]


**(3)** Display the shape of the array and explain what it means.

In [ ]:
print(house.shape)
print(house_new.shape)

#We have 10 houses and each has 3 attributes which are square ot it, number of rooms and price.

(3, 10)
(10, 3)


**(4)** Write a function that returns an array of ones with zeros where both row and column numbers are even. Sample array is below. Number of rows and columns will be entered as parameters.

```python
    shape(6 x 5) --> [[1   1   1   1   1]
                      [1   0   1   0   1]
                      [1   1   1   1   1]
                      [1   0   1   0   1]
                      [1   1   1   1   1]
                      [1   0   1   0   1]]
```